t0	DS.W 70
	ORG 	$140
STAR:
e0:
e1:
* ----COPY GLOBAL VARIABLE ON THE STACK----
	MOVE.L #69, D6
	LEA t0, A5
MOVE_LOOP_t0:
	MOVE.W (A5)+, -(A7)
	DBF D6, MOVE_LOOP_t0

* ----COPY LOCAL VARIABLE ON THE STACK----
	MOVE.L #0, D6
	MOVE.L #-3, A5
	ADD.L A6, A5
MOVE_LOOP_t7:
	MOVE.W (A5), -(A7)
	SUB.L #1, A5
	DBF D6, MOVE_LOOP_t7

	JSR e0 * ----FUNCTION CALL----
	END STAR
